service: serverless-slack

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  stackName: ${self:service}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  slack:
    handler: bin/main
    name: ${self:service}
    environment:
      SLACK_WEB_HOOK: ${env:SLACK_WEB_HOOK}
